unlabel/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('artist/<str:username>/', views.artist, name='artist'),
    path('album/<int:album_id>/', views.album, name='album'),
    path('add-album/<int:artist_id>/', views.add_album, name='add_album'),
    path('edit-album/<int:album_id>/', views.edit_album, name='edit_album'),
    path('edit-profile/<str:username>/', views.edit_profile, name='edit_profile'),
    path('change-password/<int:user_id>/', views.change_password, name='change_password'),
    path('music-visibility/<int:artist_id>/', views.music_visibility, name='music_visibility'),
    path('make-admin/<int:artist_id>/', views.make_admin, name='make_admin'),
    path('remove-admin/<int:artist_id>/', views.remove_admin, name='remove_admin'),
    path('artists/', views.artists, name='artists'),
    path('explore/<sort>/', views.explore, name='explore'),
    path('search/', views.search, name='search'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/<int:album_id>/', views.delete, name='delete'),
    path('album/get_lyrics/', views.get_lyrics, name='get_lyrics'),
    path('album/add_lyrics/', views.add_lyrics, name='add_lyrics'),
    path('album/add_comment/', views.add_comment, name='add_comment'),
    path('album/delete_comment/', views.delete_comment, name='delete_comment'),
    path('album/edit_comment/', views.edit_comment, name='edit_comment')
]

unlabel_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('unlabel.urls', namespace='unlabel')),
]

unlabel/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Artist, AlbumList, SongsList, Comments, Action
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate


# Create your views here.
def home(request):
    artist_list = Artist.objects.all()
    albums = AlbumList.objects.all()
    album_list = []
    for album in albums:
        if album.artist.music_visibility == 'SM':
            album_list.append(album)

    if request.session.get("username", False):
        user = User.objects.get(username=request.session['username'])
        actions = Action.objects.filter(user=user)

        for user_album in user.artist.albumlist_set.all():
            query = Action.objects.filter(target_id=user_album.id)
            actions = actions | query

        return render(request, 'unlabel/site/index.html',
                      {"artist_list": artist_list, "album_list": album_list[:5], "actions": actions})

    else:
        return render(request, 'unlabel/site/index.html', {"artist_list": artist_list})


def artist(request, username):
    _artist = Artist.objects.get(user__username=username)
    albums = _artist.albumlist_set.all()
    actions = Action.objects.filter(user=_artist.user)

    for album in albums:
        album.songs = album.songslist_set.all()

    if actions:
        return render(request, 'unlabel/site/artist.html', {"artist": _artist, "albums": albums, "actions": actions})

    else:
        return render(request, 'unlabel/site/artist.html', {"artist": _artist, "albums": albums})


def album(request, album_id):
    this_album = AlbumList.objects.get(id=album_id)

    if this_album.artist.music_visibility == 'HM':
        return redirect('unlabel:home')

    else:
        songs = this_album.songslist_set.order_by('songName')
        artist_name = this_album.artist.artistName
        comments = this_album.comments_set.all()

        if request.session.get("username", False):
            user = User.objects.get(username=request.session['username'])
            return render(request, 'unlabel/site/detail.html',
                          {"album": this_album, "songs": songs, "artist_name": artist_name, "comments": comments,
                           "user": user})

        else:
            return render(request, 'unlabel/site/detail.html',
                          {"album": this_album, "songs": songs, "artist_name": artist_name, "comments": comments})


def add_album(request, artist_id):
    artist = Artist.objects.get(id=artist_id)
    if request.session.get("username", False) and (artist.user.username == request.session['username']):
        if request.method == "POST":
            albumArt = request.POST.get("album-art")
            albumName = request.POST.get("album-name")
            songs = request.POST.getlist("song-name")
            songs = [i for i in songs if i]
            this_artist = Artist.objects.get(id=artist_id)
            new_album = AlbumList(
                albumName=albumName,
                albumArt=albumArt,
                num_of_songs=len(songs),
                artist=this_artist,
            )
            new_album.save()

            for song in songs:
                new_song = SongsList(songName=song, album=new_album)
                new_song.save()

            action = Action(
                user=artist.user,
                verb="added the album",
                target=new_album
            )
            action.save()

            messages.add_message(request, messages.SUCCESS, 'Album added successfully!')
            return redirect('unlabel:album', album_id=new_album.id)

        else:
            _artist = Artist.objects.get(id=artist_id)
            return render(request, 'unlabel/site/add-album.html', {"artist": _artist})

    else:
        return redirect('unlabel:home')


def edit_album(request, album_id):
    album = AlbumList.objects.get(id=album_id)
    songs = album.songslist_set.all()

    if (request.session.get("username", False)) and (request.session['role'] == 'regular') and (
            album.artist.user.username == request.session['username']):
        if request.method == "POST":
            albumArt = request.POST.get("album-art")
            albumName = request.POST.get("album-name")
            songs = request.POST.getlist("song-name")
            songs = [i for i in songs if i]
            # this_artist = Artist.objects.get(id=album.artist.id)
            get_album = AlbumList.objects.get(id=album_id)
            get_album.albumName = albumName
            get_album.albumArt = albumArt
            get_album.num_of_songs = len(songs)
            get_album.save()

            get_album.songslist_set.all().delete()
            for song in songs:
                new_song = SongsList(songName=song, album=get_album)
                new_song.save()

            action = Action(
                user=get_album.artist.user,
                verb="edited the album",
                target=get_album
            )
            action.save()

            messages.add_message(request, messages.INFO, 'Album edited successfully.')
            return redirect('unlabel:album', album_id=get_album.id)
        else:
            return render(request, 'unlabel/site/edit-album.html', {"album": album, "songs": songs})

    else:
        return redirect('unlabel:home')


def edit_profile(request, username):
    artist = Artist.objects.get(user__username=username)
    # Check if user is logged in
    if request.session.get("username", False):

        if (request.session['role'] == 'admin') or (artist.user.username == request.session['username']):
            if request.method == "POST":
                artistImage = request.POST.get("artist-image")
                artistName = request.POST.get("display-name")
                email = request.POST.get("email")
                bio = request.POST.get('bio')

                artist.artistImage = artistImage
                artist.artistName = artistName
                artist.user.email = email
                artist.description = bio
                artist.user.save()
                artist.save()

                action = Action(
                    user=artist.user,
                    verb="edited their profile",
                )
                action.save()

                # messages.add_message(request, messages.INFO, 'Album edited successfully.')
                return redirect('unlabel:artist', username=username)
            else:
                return render(request, 'unlabel/site/edit-profile.html', {"user": artist.user})
        else:
            return redirect('unlabel:home')
    else:
        return redirect('unlabel:home')


def change_password(request, user_id):
    user = User.objects.get(id=user_id)
    new_password = request.POST.get('password')
    user.set_password(new_password)
    user.save()
    # Logout user
    del request.session['username']
    del request.session['role']
    return redirect('unlabel:home')


def music_visibility(request, artist_id):
    artist = Artist.objects.get(id=artist_id)
    artist.music_visibility = request.POST.get('music-visibility')
    artist.save()
    return redirect('unlabel:artist', username=artist.user.username)


def remove_admin(request, artist_id):
    artist = Artist.objects.get(id=artist_id)
    artist.role = 'regular'
    artist.save()
    return redirect('unlabel:artist', username=artist.user.username)


def make_admin(request, artist_id):
    artist = Artist.objects.get(id=artist_id)
    artist.role = 'admin'
    artist.save()
    return redirect('unlabel:artist', username=artist.user.username)


def explore(request, sort):
    albums = AlbumList.objects.order_by(sort)
    album_list = []
    for album in albums:
        if album.artist.music_visibility == 'SM':
            album_list.append(album)
    return render(request, 'unlabel/site/list.html', {"album_list": album_list})


def artists(request):
    artist_list = Artist.objects.all()
    return render(request, 'unlabel/site/artists.html', {"artist_list": artist_list})


def delete(request, album_id):
    album = AlbumList.objects.get(id=album_id)
    album.songslist_set.all().delete()
    album.delete()
    messages.add_message(request, messages.WARNING, 'Deletion successful.')
    return redirect('unlabel:explore')


def get_lyrics(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == 'POST':
        song_id = request.POST.get('song_id')
        song = SongsList.objects.get(id=song_id)
        return JsonResponse({'success': 'success', 'song_lyrics': song.lyrics}, status=200)


def add_lyrics(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == 'POST':
        song_id = request.POST.get('song_id')
        song = SongsList.objects.get(id=song_id)
        lyrics = request.POST.get('lyrics')
        song.lyrics = lyrics
        song.save()
        action = Action(
            user=song.album.artist.user,
            verb="added lyrics for",
            target=song
        )
        action.save()
        return JsonResponse({'success': 'success', 'song_lyrics': song.lyrics}, status=200)


def add_comment(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == 'POST':
        album_id = request.POST.get('album_id')
        comment = request.POST.get('comment')

        album = AlbumList.objects.get(id=album_id)
        user = User.objects.get(username=request.session['username'])

        new_comment = Comments(
            user=user,
            album=album,
            body=comment
        )
        new_comment.save()

        action = Action(
            user=user,
            verb="commented on",
            target=album
        )
        action.save()

templates/unlabel/site/artist.html
{% extends 'unlabel/base.html' %}
{% block page-title %}Artist{% endblock %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static "css/artist.css" %}"/>
    <link rel="stylesheet" href="{% static "css/feed.css" %}"/>
{% endblock %}

{% block content %}
    {#    <section >#}
    {#      <div class="cover-image"></div>#}
    {#    </section>#}
    <section class="artist-info">
        <div>
            <div class="profile-image">
                <img src="{% static artist.artistImage %}" alt=""/>
            </div>
            <div class="artist-text">
                <div style="display: flex; align-items: center; margin-bottom: 10px">
                    <h1>{{ artist.artistName }} @{{ artist.user.username }} </h1>
                    {% if request.session.role == 'admin' %}
                        <div class="admin-role">

                            {% if artist.role == 'regular' %}
                                <form method="post" action="{% url 'unlabel:make_admin' artist.id %}">
                                    {% csrf_token %}
                                    <button type="submit">Make admin</button>
                                </form>
                            {% else %}
                                <form method="post" action="{% url 'unlabel:remove_admin' artist.id %}">
                                    {% csrf_token %}
                                    <button type="submit">Remove admin</button>
                                </form>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>

                <div>
                    <p>
                        {{ artist.description }}
                    </p>
                </div>
            </div>
        </div>
        <div class="links">
            {#<button onclick="window.location.href='{% url 'unlabel:forum' %}';">Forum</button>#}
            {% if request.session.role == 'regular' and artist.user.username == request.session.username or request.session.role == 'admin' %}
                <form action="{% url 'unlabel:edit_profile' artist.user.username %}">
                    <button class="edit-profile">Edit Profile</button>
                </form>
            {% endif %}

            <div>
                {% if request.session.role == 'regular' and artist.user.username == request.session.username or request.session.role == 'admin' %}
                    <form method="post" action="{% url 'unlabel:music_visibility' artist.id %}">
                        {% csrf_token %}
                        <input {% if artist.music_visibility == 'SM' %} checked {% endif %} id="SM" value="SM"
                                                                        name="music-visibility" type="radio"
                                                                        onchange="this.form.submit()">
                        <label for="SM">Show music</label><br>

                        <input {% if artist.music_visibility == 'HM' %} checked {% endif %} id="HM" value="HM"
                                                                        name="music-visibility" type="radio"
                                                                        onchange="this.form.submit()">
                        <label for="HM">Hide music</label>


                    </form>
                {% endif %}
            </div>

            <button>Support</button>
            <div class="social-media">
                <i class="fab fa-facebook-square"></i>
                <i class="fab fa-youtube"></i>
                <i class="fab fa-twitter-square"></i>
            </div>
        </div>
    </section>

    {#  CONTENT   #}
    <section class="content">

        {# Left Content    #}
        <div class="left">
            {#            <div class="song-player">#}
            {#                <div>#}
            {#                    <div class="container-1">#}
            {#                        <div>#}
            {#                            <h2>{{ albums.1.songs.0.songName }}</h2>#}
            {#                            <p>{{ albums.1.albumName }}</p>#}
            {#                        </div>#}
            {#                        <div class="controls">#}
            {#                            <i class="fas fa-backward">&nbsp;</i>&nbsp;<i#}
            {#                                class="fas fa-play"#}
            {#                        >&nbsp;<i class="fas fa-forward"></i#}
            {#                        ></i>#}
            {#                        </div>#}
            {#                    </div>#}
            {#                    <div class="song-player-bar">song player bar</div>#}
            {#                </div>#}
            {#                <div class="song-image">#}
            {#                    <img src="{% static albums.1.albumArt %}" alt="" style="width: 60px"/>#}
            {#                </div>#}
            {#            </div>#}

            {# Album List #}

            <div class="albums">
                <p>Albums</p>

                {% if not albums %}
                    <p style="font-size: 16px; background-color: #ff0202; padding: 3px; margin-top: 10px">No albums
                        added yet!</p>
                {% endif %}
                {% if artist.music_visibility == 'SM' %}
                    <div class="album-list">

                        {% for album in albums %}
                            <div>
                                <a href="{% url 'unlabel:album' album.id %}">
                                    <img src="{% static album.albumArt %}" alt=""/>

                                </a>
                                <p>{{ album.albumName }}</p>


                                {# Edit Album #}
                                {% if request.session.role == 'regular' and artist.user.username == request.session.username %}
                                    <form action="{% url 'unlabel:edit_album' album.id %}">
                                        <button class="edit">Edit</button>
                                    </form>
                                {% endif %}

                                {# Delete #}
                                {% if request.session.role == 'admin' %}
                                    <form class="delete" method="post" action="{% url 'unlabel:delete' album.id %}">
                                        {% csrf_token %}
                                        <input value="{{ album.id }}" name="albumId" type="hidden">
                                        <button type="submit" onclick="return confirm('Do you want to delete?')">Delete
                                        </button>
                                    </form>

                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                {#Add Album#}
                {% if request.session.role == 'regular' and artist.user.username == request.session.username %}
                    <form action="{% url 'unlabel:add_album' artist.id %}">
                        <button class="add-new">Add new album</button>
                    </form>
                {% endif %}
            </div>

        </div>

        <div class="feed">
            {% include "unlabel/site/feed.html" %}
        </div>


        <div class="right">
            <p>Recent Supporters</p>
            <ul class="recent-supporters">
                <li>
                    <img src="{% static "avatars/alex-suprun-ZHvM3XIOHoE-unsplash.jpg" %}" alt=""/>
                </li>
                <li>
                    <img src="{% static "avatars/ben-parker-OhKElOkQ3RE-unsplash.jpg" %}" alt=""/>
                </li>
                <li>
                    <img src="{% static "avatars/leio-mclaren-L2dTmhQzx4Q-unsplash.jpg" %}" alt=""/>
                </li>
                <li>
                    <img src="{% static "avatars/nicolas-horn-MTZTGvDsHFY-unsplash.jpg" %}" alt=""/>
                </li>
                <li>
                    <img src="{% static "avatars/sigmund-jzz_3jWMzHA-unsplash.jpg" %}" alt=""/>
                </li>
            </ul>
        </div>
    </section>

{% endblock %}

templates/unlabel/site/detail.html
{% extends 'unlabel/base.html' %}
{% load humanize %}
{% block page-title %}Add Album{% endblock %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static "css/album.css" %}"/>{% endblock %}
{% block js %}
    <script src="{% static "js/album.js" %}"></script>
{% endblock %}
{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <section class="artist-info">
        <div>
            <div class="profile-image">
                <img src="{% static album.albumArt %}" alt=""/>
            </div>
            <div class="artist-text">
                <div><h1>{{ album.albumName }}</h1></div>
                <div>
                    <p>by <a class="artist-link" href="{% url 'unlabel:artist' album.artist.user.username %}">{{ artist_name }}</a>
                    </p>
                    <br/>
                    <p>
                        {% if album.num_of_songs == 1 %}
                            1 song
                        {% else %}
                            {{ album.num_of_songs }} songs
                        {% endif %}
                    </p><br/>
                    <p>
                        Published on: {{ album.published }}
                    </p>
                    {# Edit Album #}
                    {% if request.session.role == 'regular' and album.artist.user.username == request.session.username %}
                        <form action="{% url 'unlabel:edit_album' album.id %}">
                            <button class="edit">Edit</button>
                        </form>
                    {% endif %}
                </div>
                <div class="links">
                    <button>Support</button>
                    <div class="social-media">
                        <i class="fab fa-facebook-square"></i>
                        <i class="fab fa-youtube"></i>
                        <i class="fab fa-twitter-square"></i>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <ol class="album-songs">
            {% for song in songs %}
                <li>
                    <div style="display: flex; justify-content: space-between">
                        <span>{{ song.songName }}</span>
                        <div style="display: flex">
                            {% if song.lyrics %}
                                <button class="get-lyrics" data-song-id="{{ song.id }}"
                                        data-ajax-url="{% url 'unlabel:get_lyrics' %}">
                                    Get Lyrics
                                </button>
                            {% else %}
                                {% if request.session.role == 'regular' and album.artist.user.username == request.session.username %}
                                <button class="add-lyrics" data-song-id="{{ song.id }}">Add lyrics</button>
                                {% endif %}
                            {% endif %}
                            <button>Play</button>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ol>
    </section>
    <section class="lyrics">
    <pre></pre>
    <div class="lyrics-form" style="display: flex;">
        <textarea></textarea>
        <button class="submit-lyrics" data-song-id="" data-ajax-url="{% url 'unlabel:add_lyrics' %}">Submit</button>
    </div>
    </section>

    {#Comments#}
    <h2>Comments</h2>

    {# User Comment #}
    {% if request.session.username %}
    <section class="user-comment">
        <div>
            <img src="{% static user.artist.artistImage %}" alt=""/>
        </div>

        <div class="comment-div">
            <div class="comment-input-div">
                <p style="margin-left: 20px">{{ user.artist.artistName }}</p>
                <div>
                    <!-- Comment Input -->
                    <input
                            class="comment-input"
                            type="text"
                            placeholder="Share your thoughts!"
                    />
                </div>
            </div>

            <div style="flex-grow: 1">
                <!-- Post Button -->
                <button data-album-id="{{ album.id }}" data-ajax-url="{% url 'unlabel:add_comment' %}" class="post-comment">Post</button>
            </div>
        </div>
    </section>
    {% endif %}

    <!-- Comments -->
    <section class="posts">
        {% if comments %}
            {% for comment in comments %}
                <div>
                    <img src="{% static comment.user.artist.artistImage %}" alt=""/>
                    <div>
                        <a style="color: white" href="{% url 'unlabel:artist' comment.user.username %}">
                            <h3>{{ comment.user.artist.artistName }}</h3></a><span
                            class="date">{{ comment.timestamp | naturaltime }}</span><br>
                        {% if user.username == comment.user.username or user.artist.role == 'admin' %}
                            <button  class="edit-comment-button">Edit
                            </button>
                            <button data-comment-id="{{ comment.id }}"
                                    data-ajax-url="{% url 'unlabel:delete_comment' %}" class="delete-comment">Delete
                            </button>
                            <br>
                        {% endif %}
                        <p class="comment-text">{{ comment.body }}</p>
                        <div style="display: none" class="edit-comment">
                            <input class="edit-comment-input">
                            <button data-comment-id="{{ comment.id }}"
                                    data-ajax-url="{% url 'unlabel:edit_comment' %}"
                                    class="save-comment">Save
                            </button>
                        </div>

                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p class="no-comments">No commments yet!</p>
        {% endif %}
    </section>

{#  SONG PLAYER  #}
    {#    <section>#}
    {#        <div class="song-player">#}
    {#            <div>#}
    {#                <div class="container-1">#}
    {#                    <div>#}
    {#                        <h2>{{ songs.0.songName }}</h2>#}
    {#                        <p>{{ album.albumName }}</p>#}
    {#                    </div>#}
    {#                    <div class="controls">#}
    {#                        <i class="fas fa-backward">&nbsp;</i>&nbsp;<i class="fas fa-play"#}
    {#                    >&nbsp;<i class="fas fa-forward"></i#}
    {#                    ></i>#}
    {#                    </div>#}
    {#                </div>#}
    {#                <div class="song-player-bar">song player bar</div>#}
    {#            </div>#}
    {#            <div class="song-image">#}
    {#                <img src="{% static "albums/jaago.jpeg" %}" alt="" style="width: 60px"/>#}
    {#            </div>#}
    {#        </div>#}
    {#    </section>#}
{% endblock %}

templates/unlabel/site/edit-profile.html
{% extends 'unlabel/base.html' %}
{% block page-title %}Edit Profile{% endblock %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static "css/add-album.css" %}"/>{% endblock %}
{% block content %}
    <main>
        <section class="left profile-data">
            <form method="post" action="{% url 'unlabel:edit_profile' user.username %}">
                {% csrf_token %}
                <p class="login">Edit profile</p>
                <div class="album-info">
                    <label for="artist-image">Album Art</label><br>
                    <input type="text" placeholder="Profile Picture" value="{{ user.artist.artistImage }}"
                           name="artist-image"
                           id="artist-image"/><span>.jpg/png</span>
                    {#                    <button>Upload</button>#}
                    <br>
                    <label for="display-name">Display Name</label><br>
                    <input required type="text" placeholder="Display Name" value="{{ user.artist.artistName }}" name="display-name"
                           id="display-name"/>
                    <br>

                    <label for="email">Email</label><br>
                    <input required type="email" placeholder="Email" value="{{ user.email }}" name="email"
                           id="email"/>
                    <br>

{#                    <label for="password">Password</label><br>#}
{#                    <input type="text" placeholder="Password" value="{{ user.password }}" name="password"#}
{#                           id="password"/>#}
{#                    <br>#}

                    <label for="bio">Bio</label><br>
                    <textarea rows="11" cols="22" placeholder="Bio" name="bio" id="bio">{{ user.artist.description }}</textarea>

                    <button class="add" type="submit">Save</button>
                </div>

                {#                <div class="songs-info">#}
                {#                    <label for="song-name">Song Names</label><br>#}
                {#                    {% for song in songs %}#}
                {##}
                {#                        <input type="text" placeholder="Song Name" value="{{ song.songName }}" name="song-name"#}
                {#                               id="song-name"/>#}
                {#                    {% endfor %}#}
                {#                </div>#}

            </form>
            <br>
            <br>
            <form method="post" action="{% url 'unlabel:change_password' user.id %}">
                {% csrf_token %}
                <div class="album-info">
                    <label for="password">New password (Optional)</label><br>
                    <input required type="password" placeholder="New password" name="password"
                           id="password"/>
                    <br>
                    <button class="add" type="submit">Change password</button>

                </div>
            </form>
        </section>
        <section class="right">
            <p>Hello,</p>{{ user.username }}
            <img src="{% static user.artist.artistImage %}">
        </section>
    </main>
{% endblock %}

templates/unlabel/site/login.html
{% extends 'unlabel/base.html' %}
{% block page-title %}Login{% endblock %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static "css/login.css" %}" />{% endblock %}

{% block content %}
 <main>
      <section class="left">
        <form method="post" action="{% url 'unlabel:login' %}">
            {% csrf_token %}
          <p class="login">Login</p>
          <input type="text" placeholder="Username" name="username"  />
          <input type="password" placeholder="Password" name="password"  />
          <button type="submit">Login</button>
        </form>
      </section>
      <section class="right">UNLABEL</section>
    </main>
{% endblock %}